language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
env:
  - DJANGO_VERSION=1.11.2
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python manage.py test musique.tests