language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO_VERSION=1.11.2
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  - python manage.py test